const FETCH_MOVIES = 'FETCH_MOVIES';
const FETCH_MOVIE = 'FETCH_MOVIE';
const FETCH_GENRES = 'FETCH_GENRES';
const SET_CURRENT_GENRE = 'SET_CURRENT_GENRE';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export {
  FETCH_MOVIES, FETCH_MOVIE, FETCH_GENRES, SET_CURRENT_GENRE, SET_CURRENT_PAGE,
};
